title: Jake Hanson # your name (or website title) here
logo: "/images/circle_headshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Theoretical physicist with a diverse skill set. Peer-reviewed papers in Cognitive Neuroscience, Entymology, and Exoplanatery Science. Ambitious, rebellious, and creative.
  <br><br>
  PhD Astrophysics
  BS Physics
  BS Astronomy
  BS Applied Mathematics
  <br><br>
  <a href="https://www.linkedin.com/in/jake-hanson-048243159/">View my LinkedIn Profile</a>
  <br><br>
  <a href="https://github.com/jakehanson">View my GitHub Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
