title: Jake Hanson # your name (or website title) here
logo: "/images/headshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Senior data scientist with a diverse skill set. Currently in charge of marketing and web optimization data for the consumer brands CreditRepair.com and Lexington Law. Astophysics PhD, BS Physics, BS Astronomy, BS Applied Mathematics.
  <br><br>
  PhD in astrophysics specializing in information theory and complex systems.
  <br><br>
  <a href="https://www.linkedin.com/in/jake-hanson-048243159/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
